### ISSUE TITLE
指定节点下的规则分流

### ISSUE THREAD

**Issue by deathnote777** [Potatso/Management#116]
### 问题描述
可以指定哪些网站走某个节点，比如domain-suffix,google.com,A   google.com走a节点
有啥用呢？
1：可以指定一些ss站的低倍率节点(省流量)看youtube之类的做大流量消耗
2：netflix及巴哈姆特动漫疯需要指定节点才能看
3：指定google相关网站为非阿里系节点，避免输入验证码。。

### 期望结果
规则可以指定节点。

**Comment by icodesign** [comment]
Duplicate #71
