### ISSUE TITLE
Cellular 环境无法使用

### ISSUE THREAD

**Issue by stanleyguan** [Potatso/Management#125]
### 问题描述
我有 Shadowsocks 和只设置 DNS（无 proxy）两个 profile。Wi-Fi 环境下均正常。Cellular 环境下 Safari 打开网页均显示 server not found。Potatso 1 当中使用同样的 shadowsocks 设置无此问题。

### 期望结果
Cellular 环境正常使用。

### Potatso 版本
2.2.4.184

### iOS 系统版本
10.3.1

**Comment by icodesign** [comment]
这个问题很奇怪，暂时没有相关报告。按理说 Potatso 对 Wi-Fi 和 Cellular 并没有区别对待。请尝试更新到最新版试一下。
