### ISSUE TITLE
Widget 经常显示“无法载入”

### ISSUE THREAD

**Issue by Contextualist** [Potatso/Management#128]
### 问题描述
打开通知中心时，Potatso2 的 widget 有一定几率在正常显示后不久显示如下：
![无法载入.PNG](https://ooo.0o0.ooo/2017/05/25/5926313f3fd1a.png)
如果不做任何处理，以后每次打开通知中心都会直接显示“无法载入”。但是，点按这个 widget 若干次后，它又会恢复正常。

### 期望结果
Widget 能稳定地显示。

### Potatso 版本
2.3.2.200

### 设备及系统版本
iPad4,4
10.3.1

**Comment by icodesign** [comment]
在 2.4.0 应该已经解决
