### ISSUE TITLE
VPN Crash

### ISSUE THREAD

**Issue by icodesign** [Potatso/Management#92]
> 使用代理观看直播流的时候容易vpn crash
> 目前遇到的有YouTube直播和斗鱼直播
> 都是观看直播时，加载视频流大约到30mbps的速度时发生。
> https://potatso.helpshift.com/admin/issue/583/

**Comment by IMAsukininaru** [comment]
我是这个反馈的提交者，
更具体的信息是，
与规则无关，全局与使用规则均会出现此问题
协议使用的是auth_aes128_md5(服务端无兼容)或auth_sha1_v4(服务端开启兼容)
混淆使用的是tls1.2_auth_ticket(服务端开启兼容)
