### ISSUE TITLE
关于导入 PCF 文件

### ISSUE THREAD

**Issue by doobom** [Potatso/Management#97]
### 问题描述
我的要导入的 PCF 含 代理节点信息 及 规则集，假如我修改 PCF 文件内的一些信息，重新导入，就会有重复的节点还有重复的规则集

### 期望结果
希望可以复盖原有的节点信息及规则集信息。

### Potatso 版本
2.1.0(175)

### iOS 系统版本
iOS 10.3.1

**Comment by icodesign** [comment]
目前这个有点难以判断是否相同，我再考虑一下

**Comment by doobom** [comment]
代理判断 host 规则集 判断 规则集名称 会不会简单点？

或是来一个清空数据？ 
:)

**Comment by icodesign** [comment]
考虑了一下，暂时不会支持，导入并不是一个核心功能点，会考虑在接下来提供一个更友好的方式编辑
